### ISSUE TITLE
[WARNING]: Deprecated `via_device` parameter

### ISSUE THREAD

**Issue by blue-bean** [alandtse/alexa_media_player#3551]
### Describe the bug

New warning with core 2026.9.0

`Detected that custom integration 'alexa_media' calls `device_registry.async_get_or_create` with a deprecated `via_device` parameter; use `via_device_id` instead at custom_components/alexa_media/helpers.py, line 217: add_devices_callback(devices, False). This will stop working in Home Assistant 2027.8.0, please create a bug report at https://github.com/alandtse/alexa_media_player/issues`

### To Reproduce

See core log

### Expected behavior

No warning

### Home Assistant Version

2026.9.0

### Alexa Media Player Version

5.5.17

### Alexa Media Player API library Version

?

### Have you entered a 52-character key for Amazon 2SV via Authenticator App login?

No

### Is the HA core integration Alexa Devices installed?

No

### Amazon Domain

amazon.com (US)

### Debug Logs (alexa_media & alexapy)

```text

```

**Comment by bonkersbrains** [comment]
Latest Core update and latest Alexa Media (5.16.0) integration update gets the following error.
Installation method Home Assistant OS
Core 2026.9.2
Supervisor 2026.09.0
Operating System 18.2
Frontend 20260826.7

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:725
Integration: Binary sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 11:25:46 AM (2 occurrences)
Last logged: 11:25:46 AM

Error adding entity None for domain binary_sensor with platform alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 190, in report_usage
    integration_frame = get_integration_frame(
        exclude_integrations=exclude_integrations
    )
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 128, in get_integration_frame
    raise MissingIntegrationFrame
homeassistant.helpers.frame.MissingIntegrationFrame

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 725, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 971, in _async_add_entity
    device = dev_reg.async_get_or_create(
        config_entry_id=self.config_entry.entry_id,
    ...<8 lines>...
        ),
    )
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 2317, in async_get_or_create
    report_usage(
    ~~~~~~~~~~~~^
        "calls `device_registry.async_get_or_create` with a deprecated "
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        breaks_in_ha_version=version,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 218, in report_usage
    _report_usage_partial()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 254, in _report_usage
    _report_usage_no_integration(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        what, core_behavior, breaks_in_ha_version, integration_frame_err
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 386, in _report_usage_no_integration
    raise RuntimeError(msg) from err
RuntimeError: Detected code that calls `device_registry.async_get_or_create` with a deprecated `via_device` parameter; use `via_device_id` instead. Please report this issue

**Comment by BastiPrivat** [comment]
Confirmed the registration error reported above with Core 2026.9.2 and Alexa Media Player 5.16.0. In addition to the existing switch warning, the newly introduced `AmazonKidsSensor.device_info` supplies `via_device` with the same identifier as the device itself. In this path the HA deprecation report raises `RuntimeError` and prevents the binary sensor from being added.

Removing only the redundant `via_device` item from `AmazonKidsSensor.device_info`, while retaining `identifiers`, resolved this registration failure locally:

```python
@property
def device_info(self):
    """Attach to the Echo device."""
    return {
        "identifiers": {(DATA_ALEXAMEDIA, self._client.unique_id)},
    }
```

After a manual Core restart, all five Kids sensors were added successfully and reported their states.

The existing draft #3553 addresses `AlexaMediaSwitch.device_info`, but does not yet include the new Kids sensor in `binary_sensor.py`. The same removal is needed there. Our local Kids-only fix leaves the general switch deprecation warning in place; it should not be taken as a complete fix for this issue.

Separately, Kids sensors also trigger the coordinator failure in #3565. A guard that skips binary sensors without a Smart Home entity ID restored coordinator polling locally.

**Comment by wesleyRaposo** [comment]
@BastiPrivat 
After making the suggested change, the thermometers from my Echo Dots reappeared in Home Assistant.
However, errors related to the integration continue to appear in Home Assistant.

**Comment by BastiPrivat** [comment]
@wesleyRaposo Thanks for confirming that the temperature sensors returned. Could you share the exact remaining error message and full traceback from after the restart, together with your HA Core and integration versions? Please redact credentials and personal information.
Did you apply only the AmazonKidsSensor.device_info change, or also the coordinator guard described in #3565?
These address separate problems: removing the redundant via_device entry fixes Kids sensor registration; the coordinator guard prevents the missing alexa_entity_id exception. The general via_device warning from AlexaMediaSwitch can still remain with those two changes.
The exact log will help distinguish that remaining warning from another runtime error.

**Comment by wesleyRaposo** [comment]
Hello, @BastiPrivat

I made the adjustment specifically for this issue. I hadn't read issue 3565 and didn't do anything related to it.
I applied the fix last night; the thermometers reappeared, and I went to sleep.
Today, the thermometers had disappeared again. I took the opportunity to update the Home Assistant core to version 2026.9.2 and performed a full restart.

The thermometers returned, and only the first message below (WARNING 1) is appearing. That call does indeed exist on line 217 of the "entity.py" file.

However, after a few minutes, a new error appeared (ERROR 1 and WARNING 2), the thermometers vanished, and Home Assistant froze.

It seems that this adjustment only works temporarily, until something else is triggered by the integration.

-------------[WARNING 1]-------------
Logger: homeassistant.helpers.frame
Fonte: helpers/frame.py:34
Ocorreu pela primeira vez: 12:42:24 (1 ocorrência)
Último log: 12:42:24

Detected that custom integration 'alexa_media' calls `device_registry.async_get_or_create` with a deprecated `via_device` parameter; use `via_device_id` instead at custom_components/alexa_media/helpers.py, line 217: add_devices_callback(devices, False). This will stop working in Home Assistant 2027.8.0, please create a bug report at https://github.com/alandtse/alexa_media_player/issues

-------------[ERROR 1]-------------
Esse erro teve origem em uma integração personalizada.

Logger: custom_components.alexa_media.coordinator
Fonte: helpers/update_coordinator.py:441
Integração: Alexa Media Player (documentação, problemas)
Ocorreu pela primeira vez: 12:52:25 (1 ocorrência)
Último log: 12:52:25

Unexpected error fetching alexa_media data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 441, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 977, in async_update_data
    entities_to_monitor.add(binary_sensor.alexa_entity_id)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AmazonKidsSensor' object has no attribute 'alexa_entity_id'

-------------[WARNING 2]-------------
Logger: py.warnings
Fonte: helpers/update_coordinator.py:568
Ocorreu pela primeira vez: 13:02:25 (4 ocorrências)
Último log: 13:02:25

/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py:568: RuntimeWarning: coroutine 'AlexaAPI.get_dnd_state' was never awaited self.last_exception = err
/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py:568: RuntimeWarning: coroutine 'AlexaAPI.get_device_preferences' was never awaited self.last_exception = err
/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py:568: RuntimeWarning: coroutine 'AlexaAPI.get_bluetooth' was never awaited self.last_exception = err
/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py:568: RuntimeWarning: coroutine 'AlexaAPI.get_devices' was never awaited self.last_exception = err

**Comment by BastiPrivat** [comment]
@wesleyRaposo Thanks for the detailed traceback. ERROR 1 confirms the separate coordinator bug in #3565: `AmazonKidsSensor` has no `alexa_entity_id`. Since you have not applied that fix, correcting device registration alone does not prevent subsequent coordinator updates from failing.

The fixes are tracked separately:
- #3567 guards the coordinator loop against binary sensors without `alexa_entity_id`.
- #3570 removes the self-referential `via_device` metadata from Kids sensors and switches.

Both PRs are currently open. #3570 alone does not include the coordinator fix.

Our equivalent local coordinator guard and Kids registration fix passed focused tests and post-restart checks on Core 2026.9.2 / integration 5.16.0. The unawaited-coroutine warnings are consistent with the coordinator update aborting. This identifies the reported integration error, but does not establish the cause of an entire Home Assistant freeze.

**Comment by wesleyRaposo** [comment]
@BastiPrivat
I included the adjustment mentioned in issue 3570 in the `__init__.py` file and restarted Home Assistant.
Everything is working for now.

**Comment by danielbrunt57** [comment]
Closing this as completed in [v5.16.1](https://github.com/alandtse/alexa_media_player/releases/tag/v5.16.1)
