### ISSUE TITLE
Device not recognized anymore

### ISSUE THREAD

**Issue by yolani** [alandtse/alexa_media_player#2878]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Since yesterday, without any updates to HA or the integration my devices all became unavailable. Several restarts and/or reloading of the integration did not solve the problem. Also deleting and re-installing the integration was not helpful. After reinstalling don't even get any device entries anymore.

**To Reproduce**

n/a

**Expected behavior**

My devices are available.

**Screenshots**

<img width="590" alt="Image" src="https://github.com/user-attachments/assets/2a656c45-f609-4abf-988c-7df48ba7bf69" />

**System details**

- Home Assistant version:
- alexa_media version (from `const.py` or HA startup log): 5.6.0
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): 1.29.5
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
- Amazon Domain: amazon.de

**Debug Logs (alexa_media & alexapy)**

This is with debug logging enabled, there is nothing more in a 30min log.

2025-03-28 08:24:11.707 ERROR (MainThread) [custom_components.alexa_media] Error fetching alexa_media data: Error communicating with API: 'NoneType' object is not subscriptable
2025-03-28 08:29:10.257 DEBUG (MainThread) [alexapy.alexahttp2] Preparing ping to https://alexa.eu.gateway.devices.a2z.com/ping
2025-03-28 08:29:10.301 DEBUG (MainThread) [alexapy.alexahttp2] Received response: 204:
2025-03-28 08:34:09.303 DEBUG (MainThread) [alexapy.alexahttp2] Preparing ping to https://alexa.eu.gateway.devices.a2z.com/ping
2025-03-28 08:34:09.345 DEBUG (MainThread) [alexapy.alexahttp2] Received response: 204:
2025-03-28 08:39:08.347 DEBUG (MainThread) [alexapy.alexahttp2] Preparing ping to https://alexa.eu.gateway.devices.a2z.com/ping
2025-03-28 08:39:08.390 DEBUG (MainThread) [alexapy.alexahttp2] Received response: 204:
2025-03-28 08:44:07.391 DEBUG (MainThread) [alexapy.alexahttp2] Preparing ping to https://alexa.eu.gateway.devices.a2z.com/ping
2025-03-28 08:44:07.436 DEBUG (MainThread) [alexapy.alexahttp2] Received response: 204:

**Additional context**

**Comment by danielbrunt57** [comment]
Have you checked that you can log into your Amazon account?

**Comment by yolani** [comment]
> Have you checked that you can log into your Amazon account?

Yes of course, by browser and the Alexa app on my phone is also working.

**Comment by yolani** [comment]
I just checked some debug logs, pretty sure I am correctly logged in, I see this here when reloading the integration 

'

2025-03-29 14:45:34.288 DEBUG (MainThread) [alexapy.alexalogin] Logged in as vonlani@gmail.com to amazon.de with id: A2C1AU2DOGC3YG
2025-03-29 14:45:34.445 DEBUG (MainThread) [alexapy.alexalogin] Domain amazon.de matches reported account domain: amazon.de
2025-03-29 14:45:34.446 DEBUG (MainThread) [alexapy.alexalogin] Login confirmed for vonlani@gmail.com - amazon.de; saving cookie to /config/.storage/alexa_media.vonlani@gmail.com.pickle
2025-03-29 14:45:34.447 DEBUG (MainThread) [alexapy.alexalogin] Saving cookie to /config/.storage/alexa_media.vonlani@gmail.com.pickle

'

**Comment by Supermario3012** [comment]
Have the same problem since yesterday. It started with the fact that the devices were unavailable. 
Did install alexa media player again twice. However no devices discovered.

**Comment by danielbrunt57** [comment]
Analyze your debug log.  
The api/phoenix call could be failing for some reason and AMP can't get your account's network details from Amazon.
It could be erroring out with 429 Too many requests or your account may have developed an error in it, which has happened before but Amazon could not figure it out.  In that case, a brand new account with all the same devices added worked fine.

**Comment by Supermario3012** [comment]
Were do I find the respective logs. In HA core I find the following:

Logger: custom_components.alexa_media
Quelle: helpers/update_coordinator.py:412
Integration: Alexa Media Player (Dokumentation, Probleme)
Erstmals aufgetreten: 13:52:44 (1 Vorkommnisse)
Zuletzt protokolliert: 13:52:44

Error fetching alexa_media data: Error communicating with API: 'NoneType' object is not subscriptable

**Comment by Supermario3012** [comment]
Just spoke to Amazon hotline for a while. They a sure that the problem lies with the HA AMP integration! I am of the same opinion. The solution can not be to always crate a new account with Amazon. 
The problem has to be looked into in more detail on the integration side.
I would offer to assist as much as I can.

**Comment by yolani** [comment]
Any further ideas on how to debug this? Issue is still present on my side. 

I'd be willing to help and produce all sorts of logs you need but I'd rather delete the integration instead of creating a new Amazon account and moving my devices there;-)

**Comment by versile2** [comment]
same problem. Reloading worked last week but is not working now. All my devices are "unavailable" everything is still solid.

**Comment by yolani** [comment]
Here is a full debug log of reloading the integration. @danielbrunt57 canyon spot anything?

[alexa_media.log](https://github.com/user-attachments/files/19682608/alexa_media.log)

**Comment by Supermario3012** [comment]
> Here is a full debug log of reloading the integration. [@danielbrunt57](https://github.com/danielbrunt57) can you spot anything?
> 
> [alexa_media.log](https://github.com/user-attachments/files/19682608/alexa_media.log)

Hi yolani,
where do you find this extensive log file? I get far less entries in the home assistant core log. 
Therefore I cannot compare my log.

**Comment by yolani** [comment]
> > Here is a full debug log of reloading the integration. [@danielbrunt57](https://github.com/danielbrunt57) can you spot anything?
> > [alexa_media.log](https://github.com/user-attachments/files/19682608/alexa_media.log)
> 
> Hi yolani, where do you find this extensive log file? I get far less entries in the home assistant core log. Therefore I cannot compare my log.

You have to enable debug logging on the integration page.

**Comment by Supermario3012** [comment]
> > > Here is a full debug log of reloading the integration. [@danielbrunt57](https://github.com/danielbrunt57) can you spot anything?
> > > [alexa_media.log](https://github.com/user-attachments/files/19682608/alexa_media.log)
> > 
> > 
> > Hi yolani, where do you find this extensive log file? I get far less entries in the home assistant core log. Therefore I cannot compare my log.
> 
> You have to enable debug logging on the integration page.

After enabling debug logging, my log looks 100% identical to yolani's log.

**Comment by danielbrunt57** [comment]
> Here is a full debug log of reloading the integration. [@danielbrunt57](https://github.com/danielbrunt57) can you spot anything?
> 
> [alexa_media.log](https://github.com/user-attachments/files/19682608/alexa_media.log)

AMP is not able to login into either amazon.de or amazon.com with the saved (pickled) cookie/token:
```
2025-04-10 12:01:56.267 DEBUG (MainThread) [alexapy.alexalogin] Attempting to register with amazon.de

2025-04-10 12:01:56.467 DEBUG (MainThread) [alexapy.alexalogin] auth response <ClientResponse(https://api.amazon.de/auth/register) [401 Unauthorized]>
<CIMultiDictProxy('Server': 'Server', 'Date': 'Thu, 10 Apr 2025 10:01:56 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '253', 'Connection': 'keep-alive', 'x-amz-rid': 'RYHY3Z34AKHJ7QCTA2SD', 'x-amzn-RequestId': '7a7d4c5a-4f46-4405-9e12-bc34ae229cb7', 'X-Amz-Date': 'Thu, 10 Apr 2025 10:01:56 GMT', 'WWW-Authenticate': 'Basic realm="api.amazon.de/auth/register"', 'Cache-Control': 'no-cache, no-store, must-revalidate', 'x-amzn-Remapped-WWW-Authenticate': 'Basic realm="api.amazon.de/auth/register"', 'Pragma': 'no-cache', 'Vary': 'Content-Type,Accept-Encoding,User-Agent', 'Strict-Transport-Security': 'max-age=47474747; includeSubDomains; preload')>
 with
{"requested_extensions": ["device_info", "customer_info"], "cookies": {"website_cookies": [], "domain": ".amazon.de"}, "registration_data": {"domain": "Device", "app_version": "2.2.556530.0", "device_type": "A2IVLV5VM2W81", "device_name": "%FIRST_NAME%'s%DUPE_STRATEGY_1ST%Alexa Media Player", "os_version": "16.6", "device_serial": "b56ed8e8c108fd1c632d377810292f37", "device_model": "iPhone", "app_name": "Alexa Media Player", "software_version": "1"}, "auth_data": {"access_token": "Atna|EwICIDWJXd80APu6b4M5L1TVfsKUsxBAmK1mI8VsniY_7NdYLs0E11b6S4nZGhzf3AGdirgK8aw0Gm9-90IcidlBHPCFxzfHxjHraZpZObSgYmSzA8wAWYuKzH6FXhMhJlodFsPNDu9ozJ57jQ3GgOeCTrmZcRV8y2gCwzgi-xz96JAfY3_PRyoa-dyB1pgFG0ls2WHwpniLlSOLmXXCQ4KU-cxAXlNu1RKuQDwafAp6PF5jfZjQnfTjaXllarJP2P_IKoyXg9tXYLN3zYuZljBrRdGrqbNohmF5xbG8UsZ8gNDpFwvZVV7Svje_5aZQxg1ph4ps4DnuIkp2iQeWlAXg8aeKV_C8-BNqadJTfAqM5SMldXd3mUlhANdqgOXJ5Z0pFn0"}, "user_context_map": {"frc": "a4KQ+RzigqHemcTO7yWULKIL+G7hjXzjThcxganh4Nt9tRLDQnVxLpXpDYr7GqaTvQ80Sw71iCbjgizM0kqhPg5A4y6Ymb728+kcsdHK+mdxChqD3/BpBqfY1ruvl5fKhfVii6Xwa+axpEVjuK9BvPs9PDdVf8yg/0i+/YRweea9ROGSehG0zLWEEcg3z8LU/8XCA2JWG6tBJDCt38cEEZcS6dxcNSVcvUu+kYg5Y/8fck3UtXk5TKm5vAF1PfKv0S0IRyxV6ONag8djiSbUg9QDRe34/HvYkFJT+KHzj//iSYoOSWIjFm+noI+ivY2gU7fs/rYT0r7qubbwHDkvU0qglkw8pcAoRT7t7JILdJycSvtHR20n9/j9nOOdrM1lf/1s4jDZLx/f1vVu0EzQVimDPZK+GykZ1g"}, "requested_token_type": ["bearer", "mac_dms", "website_cookies"]}

2025-04-10 12:01:56.468 DEBUG (MainThread) [alexapy.alexalogin] Attempting to register with amazon.com

2025-04-10 12:01:56.851 DEBUG (MainThread) [alexapy.alexalogin] auth response <ClientResponse(https://api.amazon.com/auth/register) [401 Unauthorized]>
<CIMultiDictProxy('Server': 'Server', 'Date': 'Thu, 10 Apr 2025 10:01:56 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '254', 'Connection': 'keep-alive', 'x-amz-rid': '3TNZWC08WNR5DBFS84J7', 'x-amzn-RequestId': 'a7b403ad-22c4-4ecb-aab2-b39007f7d3bb', 'X-Amz-Date': 'Thu, 10 Apr 2025 10:01:56 GMT', 'WWW-Authenticate': 'Basic realm="api.amazon.com/auth/register"', 'Cache-Control': 'no-cache, no-store, must-revalidate', 'x-amzn-Remapped-WWW-Authenticate': 'Basic realm="api.amazon.com/auth/register"', 'Pragma': 'no-cache', 'Vary': 'Content-Type,Accept-Encoding,User-Agent', 'Strict-Transport-Security': 'max-age=47474747; includeSubDomains; preload')>
 with
{"requested_extensions": ["device_info", "customer_info"], "cookies": {"website_cookies": [], "domain": ".amazon.com"}, "registration_data": {"domain": "Device", "app_version": "2.2.556530.0", "device_type": "A2IVLV5VM2W81", "device_name": "%FIRST_NAME%'s%DUPE_STRATEGY_1ST%Alexa Media Player", "os_version": "16.6", "device_serial": "b56ed8e8c108fd1c632d377810292f37", "device_model": "iPhone", "app_name": "Alexa Media Player", "software_version": "1"}, "auth_data": {"access_token": "Atna|EwICIDWJXd80APu6b4M5L1TVfsKUsxBAmK1mI8VsniY_7NdYLs0E11b6S4nZGhzf3AGdirgK8aw0Gm9-90IcidlBHPCFxzfHxjHraZpZObSgYmSzA8wAWYuKzH6FXhMhJlodFsPNDu9ozJ57jQ3GgOeCTrmZcRV8y2gCwzgi-xz96JAfY3_PRyoa-dyB1pgFG0ls2WHwpniLlSOLmXXCQ4KU-cxAXlNu1RKuQDwafAp6PF5jfZjQnfTjaXllarJP2P_IKoyXg9tXYLN3zYuZljBrRdGrqbNohmF5xbG8UsZ8gNDpFwvZVV7Svje_5aZQxg1ph4ps4DnuIkp2iQeWlAXg8aeKV_C8-BNqadJTfAqM5SMldXd3mUlhANdqgOXJ5Z0pFn0"}, "user_context_map": {"frc": "a4KQ+RzigqHemcTO7yWULKIL+G7hjXzjThcxganh4Nt9tRLDQnVxLpXpDYr7GqaTvQ80Sw71iCbjgizM0kqhPg5A4y6Ymb728+kcsdHK+mdxChqD3/BpBqfY1ruvl5fKhfVii6Xwa+axpEVjuK9BvPs9PDdVf8yg/0i+/YRweea9ROGSehG0zLWEEcg3z8LU/8XCA2JWG6tBJDCt38cEEZcS6dxcNSVcvUu+kYg5Y/8fck3UtXk5TKm5vAF1PfKv0S0IRyxV6ONag8djiSbUg9QDRe34/HvYkFJT+KHzj//iSYoOSWIjFm+noI+ivY2gU7fs/rYT0r7qubbwHDkvU0qglkw8pcAoRT7t7JILdJycSvtHR20n9/j9nOOdrM1lf/1s4jDZLx/f1vVu0EzQVimDPZK+GykZ1g"}, "requested_token_type": ["bearer", "mac_dms", "website_cookies"]}

2025-04-10 12:01:56.851 DEBUG (MainThread) [alexapy.alexalogin] Unable to register with ['amazon.de', 'amazon.com']

2025-04-10 12:01:57.043 DEBUG (MainThread) [alexapy.alexalogin] capabilities response <ClientResponse(https://api.amazonalexa.com/v1/devices/@self/capabilities) [403 Forbidden]>
```

Why, I don't know.  Try shutting down HA, removing your `/config/storage/*.pickle` file which contains the last authenticated session cookies (encrypted), then restart HA.  This will force AMP to reauthenticate with your saved credentials.

**Comment by Supermario3012** [comment]
Hi Daniel,
although my log looks very similar I get a positive response in my log when AMP is attempting to log in:
`2025-04-11 10:23:57.121 DEBUG (MainThread) [alexapy.alexalogin] Attempting to register with amazon.de
2025-04-11 10:23:57.743 DEBUG (MainThread) [alexapy.alexalogin] auth response <ClientResponse(https://api.amazon.de/auth/register) [200 OK]>`

However, still no devices or entities found.

Could you have a look at my log, maybe there is something else that could help all of us.

[alexa_media_2025-04-11.log](https://github.com/user-attachments/files/19702622/alexa_media_2025-04-11.log)

**Comment by yolani** [comment]
I deleted the pickle file but it did not help so far. 

I noticed something else: I just deleted the integration, and after a HA restart all the devices and entities are still present in the various registries in .storage. Is that expected behavior, will this cause an issue?

**Comment by danielbrunt57** [comment]
> Could you have a look at my log, maybe there is something else that could help all of us.
> 
> [alexa_media_2025-04-11.log](https://github.com/user-attachments/files/19702622/alexa_media_2025-04-11.log)

Your error starts here withe the `500:Internal Server Error:application/json`:

2025-04-11 10:23:59.278 DEBUG (MainThread) [alexapy.alexaapi] m******d@h*********m: static GET: https://alexa.amazon.de/api/phoenix returned 500:Internal Server Error:application/json
2025-04-11 10:23:59.278 DEBUG (MainThread) [alexapy.alexaapi] api_calls: 4
2025-04-11 10:23:59.279 DEBUG (MainThread) [alexapy.alexaapi] Returning None due to status: 500
2025-04-11 10:23:59.279 DEBUG (MainThread) [alexapy.alexaapi] m******d@h*********m: get_network_details response: None
2025-04-11 10:23:59.302 DEBUG (MainThread) [alexapy.alexaapi] m******d@h*********m: static GET: https://alexa.amazon.de/api/bluetooth?cached=false returned 200:OK:application/json
2025-04-11 10:23:59.302 DEBUG (MainThread) [alexapy.alexaapi] api_calls: 5
2025-04-11 10:23:59.303 DEBUG (MainThread) [alexapy.alexahttp2] HTTP2 Connection Closed.
2025-04-11 10:23:59.305 DEBUG (MainThread) [custom_components.alexa_media] m******d@h*********m: Close requested; will not reconnect http2
2025-04-11 10:23:59.305 DEBUG (MainThread) [alexapy.alexahttp2] Received raw message: --------abcde123

2025-04-11 10:23:59.350 DEBUG (MainThread) [alexapy.alexahttp2] Received response: 204:
2025-04-11 10:23:59.482 DEBUG (MainThread) [alexapy.alexaapi] m******d@h*********m: static GET: https://alexa.amazon.de/api/device-preferences returned 200:OK:application/json
2025-04-11 10:23:59.482 DEBUG (MainThread) [alexapy.alexaapi] api_calls: 6
2025-04-11 10:23:59.483 DEBUG (MainThread) [custom_components.alexa_media] Alexa entities have been loaded. Prepared for discovery.
2025-04-11 10:23:59.483 ERROR (MainThread) [custom_components.alexa_media] Error fetching alexa_media data: Error communicating with API: 'NoneType' object is not subscriptable
2025-04-11 10:23:59.483 DEBUG (MainThread) [custom_components.alexa_media] Finished fetching alexa_media data in 0.542 seconds (success: False)
```
The static GET is a shared routine in alexapy's alexaapi.py code and is called from another place with parameters specifying URL, etc.  That static GET to the `phoenix` URL is not getting the expected JSON response so the calling routine is being trapped with a failure of '500'.  Additional debug statements would have to be added to ascertain what exactly is in the response from Amazon to try and guess what might be wrong.  I'll try and make time in the next day or so to look more into additional debug statements and where to put them since it's 4:00 am here now!

**Comment by danielbrunt57** [comment]
It looks like it might be here in `alexapy/alexaapi.py` at line 1696:

```python
    @staticmethod
    @_catch_all_exceptions
    async def get_guard_details(login: AlexaLogin) -> Optional[dict[str, Any]]:
        """Get Alexa Guard details.

        Args:
        login (AlexaLogin): Successfully logged in AlexaLogin

        Returns json

        """
        response = await AlexaAPI._static_request("get", login, "/api/phoenix")
        # _LOGGER.debug("%s: Response: %s", hide_email(login.email),
        #               await response.json(content_type=None))
        return (
            json.loads((await response.json(content_type=None))["networkDetail"])
            if response
            else None
        )
```
You could try uncommenting the two existing _LOGGER_ lines at 1708-1709, restart HA and check the logs again.
That will likely fail though if the response is not JSON so maybe just change the uncommented `_LOGGER` lines to just output the raw response:
```
        _LOGGER.debug("%s: Response: %s", hide_email(login.email),
                      response))
```

**Comment by danielbrunt57** [comment]
If this truly is the failing point then the code will have to be modified to test if the response is JSON before trying to execute json.loads.

BTW, it's most likely the next shared routine, `get_network_details`, that is failing but it simply calls the `guard` one since they both reference `/api/phoenix`.
```python
    @staticmethod
    @_catch_all_exceptions
    async def get_network_details(login: AlexaLogin) -> Optional[dict[str, Any]]:
        """Get the network of devices that Alexa is aware of. This is the same as calling get_guard_details().

        Args:
        login: (AlexaLogin): Successfully logged in AlexaLogin

        Returns json
        """
        network_detail = await AlexaAPI.get_guard_details(login)
        _LOGGER.debug(
            "%s: get_network_details response: %s",
            hide_email(login.email),
            network_detail,
        )
        return network_detail
```

**Comment by yolani** [comment]
I think you might be on to something:

`This error originated from a custom integration.

Logger: custom_components.alexa_media
Source: helpers/update_coordinator.py:412
integration: Alexa Media Player (documentation, issues)
First occurred: 1:51:24 PM (1 occurrences)
Last logged: 1:51:24 PM

Error fetching alexa_media data: Error communicating with API: 'NoneType' object has no attribute 'json'`

**Comment by Supermario3012** [comment]
Where do I find the file `alexapy/alexaapi.py` to modify it?

**Comment by danielbrunt57** [comment]
> Where do I find the file `alexapy/alexaapi.py` to modify it?

You have to get into the homeassistant container.  I use this Add-on:

<img width="184" alt="Image" src="https://github.com/user-attachments/assets/8f9d3842-f8c8-4171-b550-54bd2e6524af" />

You have to disable Protected mode...

<img width="623" alt="Image" src="https://github.com/user-attachments/assets/ebe208ed-c050-4bdc-bb1d-eaeaf0d8bb15" />

Then from the HA command line, I run `docker exec -it homeassistant bash` to get to the HA command line's parent container.

**Comment by yolani** [comment]
My devices are back with 5.7.0, hooray;-)

**Comment by Supermario3012** [comment]
All working again after installing 5.7.0.
All Devices and Entities are back! 
Thanks Daniel

**Comment by yolani** [comment]
One last note on this, since updating to 5.7.0 the integration does not pickup the temperature sensor of my echo anymore.
