### ISSUE TITLE
[Bug]: Bluetooth Light Entities Paired with Alexa Devices Offline

### ISSUE THREAD

**Issue by RadDip** [alandtse/alexa_media_player#3564]
### Describe the bug

Hello:

After updating to V5.16.0, my Bluetooth lights connected to my various Alexa devices seen as entities within the Alexa Integration become unavailable.  Had to fall back to the previous version for them to become available again.

### To Reproduce

1. Clicked on Alexa Media Player Integration
2.  Searched the specific entities.  In this case (6) lights
3. Exclamation point indicated on all devices
4. Clicked on each of them and confirmed they were unavailable to control

### Expected behavior

Devices entities to be available to control.

### Home Assistant Version

2026.9.1

### Alexa Media Player Version

5.16.0

### Alexa Media Player API library Version

DK

### Have you entered a 52-character key for Amazon 2SV via Authenticator App login?

No

### Is the HA core integration Alexa Devices installed?

No

### Amazon Domain

amazon.com (US)

### Debug Logs (alexa_media & alexapy)

```text

```

**Comment by cdmlb** [comment]
Same issue

Started right after updating to v5.16.0

Installation method Home Assistant OS
Core 2026.9.2
Supervisor 2026.09.0
Operating System 18.2
Frontend 20260826.7

This error originated from a custom integration.

Logger: custom_components.alexa_media.coordinator
Source: helpers/update_coordinator.py:441
Integration: Alexa Media Player (documentation, issues)
First occurred: 2:23:18 PM (2 occurrences)
Last logged: 2:38:18 PM

Unexpected error fetching alexa_media data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 441, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 977, in async_update_data
    entities_to_monitor.add(binary_sensor.alexa_entity_id)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AmazonKidsSensor' object has no attribute 'alexa_entity_id'


Logger: py.warnings
Source: helpers/update_coordinator.py:568
First occurred: 2:38:18 PM (4 occurrences)
Last logged: 2:38:18 PM

/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py:568: RuntimeWarning: coroutine 'AlexaAPI.get_dnd_state' was never awaited self.last_exception = err
/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py:568: RuntimeWarning: coroutine 'AlexaAPI.get_device_preferences' was never awaited self.last_exception = err
/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py:568: RuntimeWarning: coroutine 'AlexaAPI.get_bluetooth' was never awaited self.last_exception = err
/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py:568: RuntimeWarning: coroutine 'AlexaAPI.get_devices' was never awaited self.last_exception = err


Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:725
Integration: Binary sensor (documentation, issues)
First occurred: 2:08:18 PM (1 occurrence)
Last logged: 2:08:18 PM

Error adding entity None for domain binary_sensor with platform alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 190, in report_usage
    integration_frame = get_integration_frame(
        exclude_integrations=exclude_integrations
    )
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 128, in get_integration_frame
    raise MissingIntegrationFrame
homeassistant.helpers.frame.MissingIntegrationFrame

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 725, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 971, in _async_add_entity
    device = dev_reg.async_get_or_create(
        config_entry_id=self.config_entry.entry_id,
    ...<8 lines>...
        ),
    )
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 2317, in async_get_or_create
    report_usage(
    ~~~~~~~~~~~~^
        "calls `device_registry.async_get_or_create` with a deprecated "
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        breaks_in_ha_version=version,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 218, in report_usage
    _report_usage_partial()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 254, in _report_usage
    _report_usage_no_integration(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        what, core_behavior, breaks_in_ha_version, integration_frame_err
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 386, in _report_usage_no_integration
    raise RuntimeError(msg) from err
RuntimeError: Detected code that calls `device_registry.async_get_or_create` with a deprecated `via_device` parameter; use `via_device_id` instead. Please report this issue

**Comment by heyjacleu** [comment]
Same. I downgraded to 5.15.7 and my bluetooth bulbs are back, and also addresses the noise from the Amazon Kids errors.

**Comment by wesleyRaposo** [comment]
It updated to version 5.16.0 today, and this error—"RuntimeWarning: coroutine 'AlexaAPI.get_dnd_state' was never awaited self.last_exception = err"—persists.
It was already present in the previous update.

The error below, also present in the previous version, remains in the current version:
"Detected that custom integration 'alexa_media' calls `device_registry.async_get_or_create` with a deprecated `via_device` parameter; use `via_device_id` instead at custom_components/alexa_media/helpers.py, line 217: add_devices_callback(devices, False). This will stop working in Home Assistant 2027.8.0, please create a bug report at https://github.com/alandtse/alexa_media_player/issues"

And two new errors have also appeared:
1) Error adding entity None for domain binary_sensor with platform alexa_media
2) Unexpected error fetching alexa_media data

**Comment by danielbrunt57** [comment]
See PR #3570 which will resolve the error in `binary_sensor.py`.

**Comment by apexbryan** [comment]
I have the same issue. I have the Amazon Echo Glow night light, that only pairs with Alexa. I've had it showing in HA through AMP for a while now, but once I updated to 5.16, it started becoming Unavailable. I would reload the integrate and it goes back online, then 15ish minutes later it goes back to Unavailable. I had to downgrade to 5.15.8 and it hasn't gone to Unavailable since

**Comment by danielbrunt57** [comment]
Closing this as completed in [v5.16.1](https://github.com/alandtse/alexa_media_player/releases/tag/v5.16.1)
