### ISSUE TITLE
Integration not getting loaded after upgrading to 2024.10.x

### ISSUE THREAD

**Issue by kaizersoje** [alandtse/alexa_media_player#2595]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

The integration is not getting loaded after upgrading to 2024.10.x

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**

- Home Assistant version:
- alexa_media version (from `const.py` or HA startup log): 4.13.4
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
- Amazon Domain: amazon.com.au

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

```
2024-10-07 07:00:24.848 ERROR (SyncWorker_1) [homeassistant.util.package] Installed version for alexapy resolved to None
2024-10-07 07:00:33.714 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.alexa_media',) inside the event loop by integration 'config' at homeassistant/components/config/config_entries.py, line 421: success = await hass.config_entries.async_set_disabled_by( (offender: /usr/src/homeassistant/homeassistant/loader.py, line 1067: ComponentProtocol, importlib.import_module(self.pkg_path)), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+config%22
2024-10-07 07:00:33.720 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'alexa_media': Unable to import component: cannot import name 'AlexaAPI' from 'alexapy' (/usr/local/lib/python3.12/site-packages/alexapy/__init__.py)
File "/config/custom_components/alexa_media/__init__.py", line 18, in <module>
from alexapy import (
ImportError: cannot import name 'AlexaAPI' from 'alexapy' (/usr/local/lib/python3.12/site-packages/alexapy/__init__.py)
File "/config/custom_components/alexa_media/__init__.py", line 18, in <module>
from alexapy import (
ImportError: cannot import name 'AlexaAPI' from 'alexapy' (/usr/local/lib/python3.12/site-packages/alexapy/__init__.py)
```

**Additional context**

**Comment by danielbrunt57** [comment]
> System details
> 
> Home Assistant version:
> alexa_media version (from const.py or HA startup log): 4.13.4
> alexapy version (from pip show alexapy in homeasssistant container or HA startup log):  ????????
> Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
> Amazon Domain: amazon.com.au

`alexapy` is not installed: `[homeassistant.util.package] Installed version for alexapy resolved to None`

Home Assistant logs should show: `2024-10-07 13:57:07.421 DEBUG (MainThread) [custom_components.alexa_media] Loaded alexapy==1.29.2`

`configuration.yaml`:
```
logger:
  logs:
    alexapy: debug
    custom_components.alexa_media: debug
```

**Comment by danielbrunt57** [comment]
After a virgin installation of the AMP custom component in HACS, it takes **_two_** restarts before alexapy is running.
The first restart just installs the alexapy dependency in `/usr/local/lib/python3.12/site-packages/alexapy/` and the 2nd restart then  activates the custom component package within the running HA core.

**Comment by danielbrunt57** [comment]
This issue might have occurred as a result of the short term block that HA imposed on AMP as v4.13.3 was causing HA to crash.  That block has now been removed...
